# Generated by Django 5.1.5 on 2025-08-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('RETRAIT', 'Retrait en dépôt'), ('COLISSIMO', 'Colissimo'), ('MONDIAL_RELAY', 'Mondial Relay')], max_length=50)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
