# Generated by Django 5.1.5 on 2025-08-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant_id',
            field=models.CharField(max_length=100),
        ),
    ]
