# Generated by Django 5.1.5 on 2025-08-27 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_variant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('retrait', 'Retrait au dépôt'), ('livraison', 'Livraison standard'), ('mondial_relay', 'Mondial Relay'), ('ups', 'UPS'), ('colissimo', 'Colissimo')], default='retrait', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_choice', to='cart.cart')),
            ],
        ),
    ]
