# Generated by Django 5.1.5 on 2025-08-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_deliverychoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Poids unitaire de la variation (en kg)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='deliverychoice',
            name='mode',
            field=models.CharField(choices=[('retrait', 'Retrait au dépôt'), ('livraison', 'Livraison standard'), ('mondial_relay', 'Mondial Relay'), ('chronopost', 'Chronopost'), ('colissimo', 'Colissimo')], default='retrait', max_length=100),
        ),
    ]
