# Generated by Django 5.1.5 on 2025-03-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_date_joined_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address complement'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='card expiry'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='last 4 digits'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='card name'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='intercom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='intercom'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='region'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='zip code'),
        ),
    ]
