name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: nature_admin
          POSTGRES_PASSWORD: NewN&Aweb25
          POSTGRES_DB: nature_animaux_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U nature_admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    # 1. Checkout du code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configuration de Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # 3. Installation des dépendances avec un environnement virtuel
    - name: Install dependencies
      run: |
        python -m venv env  # ✅ Création de l'environnement virtuel
        env/bin/pip install --upgrade pip
        env/bin/pip install -r requirements.txt  # ✅ Correction du chemin

    # 4. Vérification que django-cors-headers est bien installé
    - name: Check installed packages
      run: |
        env/bin/pip show django-cors-headers || (echo "❌ django-cors-headers non installé !" && exit 1)

    # 5. Attente des services PostgreSQL et MongoDB
    - name: Wait for PostgreSQL and MongoDB
      run: |
        while ! nc -z localhost 5432; do sleep 1; done
        while ! nc -z localhost 27017; do sleep 1; done

    # 6. Vérification de l'intégrité de Django
    - name: Run Django check
      run: |
        cd backend
        ../env/bin/python manage.py check  # ✅ Vérifie si Django démarre sans erreur

    # 7. Exécution des migrations
    - name: Run migrations
      run: |
        cd backend
        ../env/bin/python manage.py migrate

    # 8. Exécution des tests unitaires
    - name: Run unit tests
      run: |
        cd backend
        ../env/bin/python manage.py test
