name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Navigate to backend directory
    - name: Navigate to backend
      working-directory: ./backend

    # 5. Run migrations (si applicable)
    - name: Run migrations
      run: |
        python manage.py migrate

    # 6. Run tests
    - name: Run unit tests
      run: |
        python manage.py test

    # 7. Run linter (flake8 ou black, choisis en fonction de ton projet)
    - name: Run Flake8
      run: |
        pip install flake8
        flake8 . --exclude=.venv --max-line-length=79
