name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: nature_admin
          POSTGRES_PASSWORD: NewN&Aweb25
          POSTGRES_DB: nature_animaux_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U nature_admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # 3. Install dependencies in Virtual Environment
    - name: Install dependencies
      run: |
        python -m venv env  # ✅ Création d'un environnement virtuel
        source env/bin/activate  # ✅ Activation de l'environnement
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # ✅ Installation depuis la racine du projet

    # 4. Check if django-cors-headers is correctly installed
    - name: Check installed packages
      run: |
        source env/bin/activate
        pip show django-cors-headers || (echo "❌ django-cors-headers non installé !" && exit 1)

    # 5. Wait for PostgreSQL and MongoDB to be ready
    - name: Wait for PostgreSQL and MongoDB
      run: |
        while ! nc -z localhost 5432; do sleep 1; done
        while ! nc -z localhost 27017; do sleep 1; done

    # 6. Run Django check (sanity test)
    - name: Run Django check
      run: |
        source env/bin/activate
        cd backend
        python manage.py check  # ✅ Vérifie si Django peut démarrer sans erreurs

    # 7. Run migrations
    - name: Run migrations
      run: |
        source env/bin/activate
        cd backend
        python manage.py migrate

    # 8. Run unit tests
    - name: Run unit tests
      run: |
        source env/bin/activate
        cd backend
        python manage.py test
