name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: nature_admin
          POSTGRES_PASSWORD: NewN&Aweb25
          POSTGRES_DB: nature_animaux_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U nature_admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # 3. Install dependencies in Virtual Environment
    - name: Install dependencies
      run: |
        set -e  # ✅ Arrête le script en cas d’erreur
        python -m venv env  # ✅ Création de l'environnement virtuel
        if [ -f env/bin/activate ]; then
          . env/bin/activate  # ✅ Activation de l'environnement sur Linux/macOS
        elif [ -f env\Scripts\activate ]; then
          env\Scripts\activate  # ✅ Activation de l'environnement sur Windows
        fi
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt  # ✅ Vérification avant installation
        else
          echo "❌ Fichier requirements.txt introuvable !" && exit 1
        fi

    # 4. Check if django-cors-headers is correctly installed
    - name: Check installed packages
      run: |
        env/bin/python -m pip show django-cors-headers || (echo "❌ django-cors-headers non installé !" && exit 1)

    # 5. Wait for PostgreSQL and MongoDB to be ready
    - name: Wait for PostgreSQL and MongoDB
      run: |
        while ! nc -z localhost 5432; do sleep 1; done
        while ! nc -z localhost 27017; do sleep 1; done

    # 6. Run Django check (sanity test)
    - name: Run Django check
      run: |
        env/bin/python backend/manage.py check || (echo "❌ Django check a échoué !" && exit 1)

    # 7. Run migrations (seulement si Django check passe)
    - name: Run migrations
      run: |
        env/bin/python backend/manage.py migrate

    # 8. Run unit tests
    - name: Run unit tests
      run: |
        env/bin/python backend/manage.py test
