name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: nature_admin
          POSTGRES_PASSWORD: NewN&Aweb25
          POSTGRES_DB: nature_animaux_db
        options: >-
          --health-cmd="pg_isready -U nature_admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Run migrations
    - name: Run migrations
      run: |
        cd backend
        python manage.py migrate

    # 5. Run unit tests
    - name: Run unit tests
      run: |
        cd backend
        python manage.py test

    # 6. Run Flake8 (linter)
    - name: Run Flake8
      run: |
        pip install flake8
        flake8 . --exclude=.venv --max-line-length=79
